CREATE TABLE Edit_BasicInfo(
    basicinfo_id             uniqueidentifier    NOT NULL,
    type_id                  nvarchar(30)        NOT NULL,
    identity_no              nvarchar(30)        NOT NULL,
    name                     nvarchar(256)       NOT NULL,
    authority_id             int                 NULL,
    sort_no                  int                 NULL,
    remarks                  nvarchar(1000)      NULL,
    status                   nchar(1)            NULL,
    revision_no              int                 DEFAULT 0 NOT NULL,
    inputter_id              uniqueidentifier    NOT NULL,
    committer_id             uniqueidentifier    NULL,
    control_flag             bit                 NULL,
    commit_date              datetime            NULL,
    phase_flag               nchar(1)            NOT NULL,
    reflect_expected_date    datetime            NOT NULL,
    reflect_date             datetime            NULL,
    regist_date              datetime            NOT NULL,
    update_date              datetime            NULL,
    delete_date              datetime            NULL,
    basicinfo_data           xml                NOT NULL,
    object_guid              nvarchar(100)       NULL,
    CONSTRAINT PK45_1 PRIMARY KEY CLUSTERED (basicinfo_id)
)
